apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
StringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: adminpass
  REPLICATION_USER: replicator
  REPLICATION_PASSWORD: replicatorpass